-- AlterTable
ALTER TABLE `ConversacionChatbot` MODIFY `estado` ENUM('CONVERSANDO', 'ELIGIENDO_SERVICIO', 'ELIGIENDO_PROFESIONAL', 'ELIGIENDO_DIA', 'ELIGIENDO_HORA', 'PIDIENDO_NOMBRE', 'CONFIRMANDO') NOT NULL;
